export const animals = [
  {
    id: 1,
    name: "Bella",
    specie: "Chien",
    breed: "Labrador",
    age: "3 ans",
    gender: "Femelle",
    chipId: "123456789012345",
    description: "Bella est une chienne énergique et affectueuse qui adore jouer et courir. Elle a besoin de beaucoup d'exercice et d'attention.",
    distinctiveTraits: "Pelage noir, yeux marron",
    weight: "30 kg",
    height: "60 cm",
    vaccines: ["Rage", "Parvovirose", "Hépatite"],
    treatments: ["Vermifuge"]
  },
  {
    id: 2,
    name: "Milo",
    specie: "Chat",
    breed: "Siamois",
    age: "2 ans",
    gender: "Mâle",
    chipId: "234567890123456",
    description: "Milo est un chat curieux et intelligent. Il aime explorer et a besoin de stimulation mentale.",
    distinctiveTraits: "Pelage crème, yeux bleus",
    weight: "5 kg",
    height: "30 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 3,
    name: "Coco",
    specie: "Perroquet",
    breed: "Ara bleu",
    age: "5 ans",
    gender: "Femelle",
    chipId: null,
    description: "Coco est un perroquet bavard et social. Elle aime interagir avec les gens et peut apprendre quelques mots.",
    distinctiveTraits: "Plumage bleu et jaune, bec noir",
    weight: "1 kg",
    height: "90 cm",
    vaccines: [],
    treatments: []
  },
  {
    id: 4,
    name: "Charlie",
    specie: "Chien",
    breed: "Beagle",
    age: "4 ans",
    gender: "Mâle",
    chipId: "345678901234567",
    description: "Charlie est un chien affectueux et joueur. Il adore les promenades et les câlins.",
    distinctiveTraits: "Pelage tricolore, yeux marron",
    weight: "10 kg",
    height: "40 cm",
    vaccines: ["Rage", "Parvovirose"],
    treatments: ["Vermifuge"]
  },
  {
    id: 5,
    name: "Luna",
    specie: "Chat",
    breed: "Maine Coon",
    age: "1 an",
    gender: "Femelle",
    chipId: "456789012345678",
    description: "Luna est une chatte douce et tranquille. Elle aime se percher en hauteur et observer son environnement.",
    distinctiveTraits: "Pelage gris, yeux verts",
    weight: "6 kg",
    height: "35 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 6,
    name: "Max",
    specie: "Chien",
    breed: "Berger Allemand",
    age: "6 ans",
    gender: "Mâle",
    chipId: "567890123456789",
    description: "Max est un chien loyal et protecteur. Il a besoin d'un maître expérimenté et d'un espace sécurisé pour se dépenser.",
    distinctiveTraits: "Pelage noir et feu, yeux marron",
    weight: "35 kg",
    height: "65 cm",
    vaccines: ["Rage", "Parvovirose", "Hépatite"],
    treatments: ["Vermifuge"]
  },
  {
    id: 7,
    name: "Ruby",
    specie: "Lapin",
    breed: "Nain",
    age: "2 ans",
    gender: "Femelle",
    chipId: null,
    description: "Ruby est une lapine curieuse et joueuse. Elle aime grignoter et explorer son environnement.",
    distinctiveTraits: "Pelage blanc, yeux rouges",
    weight: "1 kg",
    height: "25 cm",
    vaccines: ["Myxomatose", "VHD"],
    treatments: ["Vermifuge"]
  },
  {
    id: 8,
    name: "Rocky",
    specie: "Chien",
    breed: "Bulldog Anglais",
    age: "5 ans",
    gender: "Mâle",
    chipId: "678901234567890",
    description: "Rocky est un chien calme et affectueux. Il aime les courtes promenades et les longues siestes.",
    distinctiveTraits: "Pelage fauve, yeux marron",
    weight: "24 kg",
    height: "40 cm",
    vaccines: ["Rage", "Parvovirose"],
    treatments: ["Vermifuge"]
  },
  {
    id: 9,
    name: "Lily",
    specie: "Chat",
    breed: "Bengal",
    age: "3 ans",
    gender: "Femelle",
    chipId: "789012345678901",
    description: "Lily est une chatte active et joueuse. Elle aime grimper et jouer avec des jouets interactifs.",
    distinctiveTraits: "Pelage tacheté, yeux verts",
    weight: "4 kg",
    height: "35 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 10,
    name: "Buddy",
    specie: "Chien",
    breed: "Golden Retriever",
    age: "2 ans",
    gender: "Mâle",
    chipId: "890123456789012",
    description: "Buddy est un chien sociable et joueur. Il adore les enfants et les autres animaux.",
    distinctiveTraits: "Pelage doré, yeux marron",
    weight: "32 kg",
    height: "60 cm",
    vaccines: ["Rage", "Parvovirose", "Hépatite"],
    treatments: ["Vermifuge"]
  },
  {
    id: 11,
    name: "Oscar",
    specie: "Chien",
    breed: "Dachshund",
    age: "4 ans",
    gender: "Mâle",
    chipId: "901234567890123",
    description: "Oscar est un chien affectueux et curieux. Il adore fouiner et jouer.",
    distinctiveTraits: "Pelage brun, yeux marron",
    weight: "8 kg",
    height: "25 cm",
    vaccines: ["Rage", "Parvovirose"],
    treatments: ["Vermifuge"]
  },
  {
    id: 12,
    name: "Nala",
    specie: "Chat",
    breed: "Persan",
    age: "5 ans",
    gender: "Femelle",
    chipId: "012345678901234",
    description: "Nala est une chatte douce et tranquille. Elle aime les caresses et les endroits confortables.",
    distinctiveTraits: "Pelage blanc, yeux bleus",
    weight: "4 kg",
    height: "30 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 13,
    name: "Oliver",
    specie: "Chien",
    breed: "Cocker Spaniel",
    age: "3 ans",
    gender: "Mâle",
    chipId: "123456789012346",
    description: "Oliver est un chien joueur et affectueux. Il aime les longues promenades et les jeux.",
    distinctiveTraits: "Pelage doré, yeux marron",
    weight: "13 kg",
    height: "40 cm",
    vaccines: ["Rage", "Parvovirose"],
    treatments: ["Vermifuge"]
  },
  {
    id: 14,
    name: "Mimi",
    specie: "Chat",
    breed: "Abyssin",
    age: "2 ans",
    gender: "Femelle",
    chipId: "234567890123457",
    description: "Mimi est une chatte active et curieuse. Elle aime explorer et jouer avec des jouets interactifs.",
    distinctiveTraits: "Pelage roux, yeux verts",
    weight: "3 kg",
    height: "30 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 15,
    name: "Pepper",
    specie: "Chien",
    breed: "Border Collie",
    age: "4 ans",
    gender: "Femelle",
    chipId: "345678901234568",
    description: "Pepper est une chienne intelligente et énergique. Elle a besoin de beaucoup d'exercice et de stimulation mentale.",
    distinctiveTraits: "Pelage noir et blanc, yeux marron",
    weight: "18 kg",
    height: "55 cm",
    vaccines: ["Rage", "Parvovirose", "Hépatite"],
    treatments: ["Vermifuge"]
  },
  {
    id: 16,
    name: "Lola",
    specie: "Chat",
    breed: "Sphynx",
    age: "3 ans",
    gender: "Femelle",
    chipId: "456789012345679",
    description: "Lola est une chatte affectueuse et sociable. Elle aime la chaleur et les câlins.",
    distinctiveTraits: "Peau nue, yeux bleus",
    weight: "4 kg",
    height: "30 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 17,
    name: "Duke",
    specie: "Chien",
    breed: "Doberman",
    age: "5 ans",
    gender: "Mâle",
    chipId: "567890123456791",
    description: "Duke est un chien loyal et protecteur. Il a besoin d'un maître expérimenté et d'un espace sécurisé.",
    distinctiveTraits: "Pelage noir et feu, yeux marron",
    weight: "40 kg",
    height: "70 cm",
    vaccines: ["Rage", "Parvovirose", "Hépatite"],
    treatments: ["Vermifuge"]
  },
  {
    id: 18,
    name: "Lily",
    specie: "Chat",
    breed: "Ragdoll",
    age: "4 ans",
    gender: "Femelle",
    chipId: "678901234567892",
    description: "Lily est une chatte douce et affectueuse. Elle aime les câlins et les endroits confortables.",
    distinctiveTraits: "Pelage blanc et gris, yeux bleus",
    weight: "5 kg",
    height: "35 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 19,
    name: "Jack",
    specie: "Chien",
    breed: "Jack Russell Terrier",
    age: "3 ans",
    gender: "Mâle",
    chipId: "789012345678903",
    description: "Jack est un chien énergique et curieux. Il aime jouer et a besoin de beaucoup d'exercice.",
    distinctiveTraits: "Pelage blanc et brun, yeux marron",
    weight: "7 kg",
    height: "30 cm",
    vaccines: ["Rage", "Parvovirose"],
    treatments: ["Vermifuge"]
  },
  {
    id: 20,
    name: "Zoe",
    specie: "Chat",
    breed: "Norvégien",
    age: "5 ans",
    gender: "Femelle",
    chipId: "890123456789014",
    description: "Zoe est une chatte douce et tranquille. Elle aime les câlins et les endroits confortables.",
    distinctiveTraits: "Pelage gris, yeux verts",
    weight: "5 kg",
    height: "35 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 21,
    name: "Baxter",
    specie: "Chien",
    breed: "Boxer",
    age: "4 ans",
    gender: "Mâle",
    chipId: "012345678901245",
    description: "Baxter est un chien joueur et affectueux. Il aime les longues promenades et les jeux.",
    distinctiveTraits: "Pelage fauve, yeux marron",
    weight: "30 kg",
    height: "60 cm",
    vaccines: ["Rage", "Parvovirose", "Hépatite"],
    treatments: ["Vermifuge"]
  },
  {
    id: 22,
    name: "Mimi",
    specie: "Chat",
    breed: "Burmese",
    age: "3 ans",
    gender: "Femelle",
    chipId: "123456789012347",
    description: "Mimi est une chatte active et curieuse. Elle aime explorer et jouer avec des jouets interactifs.",
    distinctiveTraits: "Pelage brun, yeux jaunes",
    weight: "4 kg",
    height: "30 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 23,
    name: "Rusty",
    specie: "Chien",
    breed: "Red Heeler",
    age: "5 ans",
    gender: "Mâle",
    chipId: "234567890123458",
    description: "Rusty est un chien intelligent et énergique. Il a besoin de beaucoup d'exercice et de stimulation mentale.",
    distinctiveTraits: "Pelage rouge, yeux marron",
    weight: "20 kg",
    height: "50 cm",
    vaccines: ["Rage", "Parvovirose", "Hépatite"],
    treatments: ["Vermifuge"]
  },
  {
    id: 24,
    name: "Chloe",
    specie: "Chat",
    breed: "Sphynx",
    age: "4 ans",
    gender: "Femelle",
    chipId: "345678901234569",
    description: "Chloe est une chatte affectueuse et sociable. Elle aime la chaleur et les câlins.",
    distinctiveTraits: "Peau nue, yeux verts",
    weight: "4 kg",
    height: "30 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 25,
    name: "Diesel",
    specie: "Chien",
    breed: "Rottweiler",
    age: "6 ans",
    gender: "Mâle",
    chipId: "456789012345680",
    description: "Diesel est un chien loyal et protecteur. Il a besoin d'un maître expérimenté et d'un espace sécurisé.",
    distinctiveTraits: "Pelage noir et feu, yeux marron",
    weight: "45 kg",
    height: "70 cm",
    vaccines: ["Rage", "Parvovirose", "Hépatite"],
    treatments: ["Vermifuge"]
  },
  {
    id: 26,
    name: "Simba",
    specie: "Chat",
    breed: "Bengal",
    age: "2 ans",
    gender: "Mâle",
    chipId: "567890123456802",
    description: "Simba est un chat actif et joueur. Il aime grimper et jouer avec des jouets interactifs.",
    distinctiveTraits: "Pelage tacheté, yeux verts",
    weight: "5 kg",
    height: "35 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 27,
    name: "Bruno",
    specie: "Chien",
    breed: "Chihuahua",
    age: "3 ans",
    gender: "Mâle",
    chipId: "678901234567813",
    description: "Bruno est un chien énergique et curieux. Il aime jouer et a besoin de beaucoup d'exercice.",
    distinctiveTraits: "Pelage brun, yeux marron",
    weight: "3 kg",
    height: "20 cm",
    vaccines: ["Rage", "Parvovirose"],
    treatments: ["Vermifuge"]
  },
  {
    id: 28,
    name: "Daisy",
    specie: "Chat",
    breed: "Birman",
    age: "4 ans",
    gender: "Femelle",
    chipId: "789012345678924",
    description: "Daisy est une chatte douce et tranquille. Elle aime les câlins et les endroits confortables.",
    distinctiveTraits: "Pelage crème et brun, yeux bleus",
    weight: "4 kg",
    height: "30 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 29,
    name: "Hunter",
    specie: "Chien",
    breed: "Pointer",
    age: "5 ans",
    gender: "Mâle",
    chipId: "890123456789035",
    description: "Hunter est un chien actif et énergique. Il aime courir et a besoin de beaucoup d'exercice.",
    distinctiveTraits: "Pelage blanc et brun, yeux marron",
    weight: "25 kg",
    height: "60 cm",
    vaccines: ["Rage", "Parvovirose", "Hépatite"],
    treatments: ["Vermifuge"]
  },
  {
    id: 30,
    name: "Lilly",
    specie: "Chat",
    breed: "Chartreux",
    age: "3 ans",
    gender: "Femelle",
    chipId: "012345678901256",
    description: "Lilly est une chatte douce et affectueuse. Elle aime les câlins et les endroits confortables.",
    distinctiveTraits: "Pelage gris, yeux orange",
    weight: "4 kg",
    height: "30 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 31,
    name: "Max",
    specie: "Chien",
    breed: "Labrador",
    age: "3 ans",
    gender: "Mâle",
    chipId: "123456789012358",
    description: "Max est un chien sociable et joueur. Il adore les enfants et les autres animaux.",
    distinctiveTraits: "Pelage noir, yeux marron",
    weight: "30 kg",
    height: "60 cm",
    vaccines: ["Rage", "Parvovirose", "Hépatite"],
    treatments: ["Vermifuge"]
  },
  {
    id: 32,
    name: "Lola",
    specie: "Chat",
    breed: "Maine Coon",
    age: "2 ans",
    gender: "Femelle",
    chipId: "234567890123469",
    description: "Lola est une chatte douce et tranquille. Elle aime se percher en hauteur et observer son environnement.",
    distinctiveTraits: "Pelage brun, yeux verts",
    weight: "6 kg",
    height: "35 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 33,
    name: "Rocky",
    specie: "Chien",
    breed: "Bulldog Français",
    age: "4 ans",
    gender: "Mâle",
    chipId: "345678901234570",
    description: "Rocky est un chien calme et affectueux. Il aime les courtes promenades et les longues siestes.",
    distinctiveTraits: "Pelage bringé, yeux marron",
    weight: "12 kg",
    height: "35 cm",
    vaccines: ["Rage", "Parvovirose"],
    treatments: ["Vermifuge"]
  },
  {
    id: 34,
    name: "Bella",
    specie: "Chat",
    breed: "Siamois",
    age: "2 ans",
    gender: "Femelle",
    chipId: "456789012345681",
    description: "Bella est une chatte curieuse et intelligente. Elle aime explorer et a besoin de stimulation mentale.",
    distinctiveTraits: "Pelage crème, yeux bleus",
    weight: "5 kg",
    height: "30 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 35,
    name: "Charlie",
    specie: "Chien",
    breed: "Beagle",
    age: "4 ans",
    gender: "Mâle",
    chipId: "567890123456892",
    description: "Charlie est un chien affectueux et joueur. Il adore les promenades et les câlins.",
    distinctiveTraits: "Pelage tricolore, yeux marron",
    weight: "10 kg",
    height: "40 cm",
    vaccines: ["Rage", "Parvovirose"],
    treatments: ["Vermifuge"]
  },
  {
    id: 36,
    name: "Lucy",
    specie: "Chat",
    breed: "Maine Coon",
    age: "3 ans",
    gender: "Femelle",
    chipId: "678901234567804",
    description: "Lucy est une chatte douce et tranquille. Elle aime se percher en hauteur et observer son environnement.",
    distinctiveTraits: "Pelage brun et blanc, yeux verts",
    weight: "6 kg",
    height: "35 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 37,
    name: "Duke",
    specie: "Chien",
    breed: "Doberman",
    age: "5 ans",
    gender: "Mâle",
    chipId: "789012345678915",
    description: "Duke est un chien loyal et protecteur. Il a besoin d'un maître expérimenté et d'un espace sécurisé.",
    distinctiveTraits: "Pelage noir et feu, yeux marron",
    weight: "40 kg",
    height: "70 cm",
    vaccines: ["Rage", "Parvovirose", "Hépatite"],
    treatments: ["Vermifuge"]
  },
  {
    id: 38,
    name: "Luna",
    specie: "Chat",
    breed: "Ragdoll",
    age: "4 ans",
    gender: "Femelle",
    chipId: "890123456789026",
    description: "Luna est une chatte douce et affectueuse. Elle aime les câlins et les endroits confortables.",
    distinctiveTraits: "Pelage blanc et gris, yeux bleus",
    weight: "5 kg",
    height: "35 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 39,
    name: "Buddy",
    specie: "Chien",
    breed: "Golden Retriever",
    age: "2 ans",
    gender: "Mâle",
    chipId: "012345678901367",
    description: "Buddy est un chien sociable et joueur. Il adore les enfants et les autres animaux.",
    distinctiveTraits: "Pelage doré, yeux marron",
    weight: "32 kg",
    height: "60 cm",
    vaccines: ["Rage", "Parvovirose", "Hépatite"],
    treatments: ["Vermifuge"]
  },
  {
    id: 40,
    name: "Simba",
    specie: "Chat",
    breed: "Siamois",
    age: "3 ans",
    gender: "Mâle",
    chipId: "123456789012478",
    description: "Simba est un chat curieux et intelligent. Il aime explorer et a besoin de stimulation mentale.",
    distinctiveTraits: "Pelage crème, yeux bleus",
    weight: "5 kg",
    height: "30 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 41,
    name: "Rocky",
    specie: "Chien",
    breed: "Boxer",
    age: "4 ans",
    gender: "Mâle",
    chipId: "234567890123579",
    description: "Rocky est un chien calme et affectueux. Il aime les courtes promenades et les longues siestes.",
    distinctiveTraits: "Pelage fauve, yeux marron",
    weight: "24 kg",
    height: "40 cm",
    vaccines: ["Rage", "Parvovirose"],
    treatments: ["Vermifuge"]
  },
  {
    id: 42,
    name: "Lily",
    specie: "Chat",
    breed: "Bengal",
    age: "3 ans",
    gender: "Femelle",
    chipId: "345678901234690",
    description: "Lily est une chatte active et joueuse. Elle aime grimper et jouer avec des jouets interactifs.",
    distinctiveTraits: "Pelage tacheté, yeux verts",
    weight: "4 kg",
    height: "35 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 43,
    name: "Oscar",
    specie: "Chien",
    breed: "Beagle",
    age: "4 ans",
    gender: "Mâle",
    chipId: "456789012345701",
    description: "Oscar est un chien affectueux et joueur. Il adore les promenades et les câlins.",
    distinctiveTraits: "Pelage tricolore, yeux marron",
    weight: "10 kg",
    height: "40 cm",
    vaccines: ["Rage", "Parvovirose"],
    treatments: ["Vermifuge"]
  },
  {
    id: 44,
    name: "Mimi",
    specie: "Chat",
    breed: "Persan",
    age: "5 ans",
    gender: "Femelle",
    chipId: "567890123456812",
    description: "Mimi est une chatte douce et tranquille. Elle aime les caresses et les endroits confortables.",
    distinctiveTraits: "Pelage blanc, yeux bleus",
    weight: "4 kg",
    height: "30 cm",
    vaccines: ["Rage", "Coryza"],
    treatments: ["Vermifuge"]
  },
  {
    id: 45,
    name: "Buddy",
    specie: "Chien",
    breed: "Labrador",
    age: "2 ans",
    gender: "Mâle",
    chipId: "678901234567925",
    description: "Buddy est un chien sociable et joueur. Il adore les enfants et les autres animaux.",
    distinctiveTraits: "Pelage doré, yeux marron",
    weight: "32 kg",
    height: "60 cm",
    vaccines: ["Rage", "Parvovirose", "Hépatite"],
    treatments: ["Vermifuge"]
  }
]
